# Generated by Django 5.2.8 on 2025-11-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique identifier for the transaction (UUID format)', max_length=255, unique=True)),
                ('transaction_timestamp', models.DateTimeField(db_index=True, help_text='Timestamp when the transaction occurred')),
                ('card_id', models.BigIntegerField(db_index=True, help_text='Identifier for the card used in the transaction')),
                ('expiry_date', models.CharField(help_text='Card expiry date in MM/YY format', max_length=10)),
                ('issuer_bank_name', models.CharField(db_index=True, help_text='Name of the bank that issued the card', max_length=255)),
                ('merchant_id', models.BigIntegerField(db_index=True, help_text='Unique identifier for the merchant')),
                ('merchant_mcc', models.IntegerField(db_index=True, help_text='Merchant Category Code (MCC)')),
                ('mcc_category', models.CharField(db_index=True, help_text="Human-readable category of the merchant (e.g., 'Grocery & Food Markets')", max_length=255)),
                ('merchant_city', models.CharField(db_index=True, help_text='City where the merchant is located', max_length=255)),
                ('transaction_type', models.CharField(db_index=True, help_text="Type of transaction (e.g., 'POS', 'Online', etc.)", max_length=50)),
                ('transaction_amount_kzt', models.DecimalField(decimal_places=2, help_text='Transaction amount in Kazakhstani Tenge (KZT)', max_digits=12)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Original amount in original currency (if different from KZT)', max_digits=12, null=True)),
                ('transaction_currency', models.CharField(help_text='Currency code of the transaction (ISO 4217)', max_length=3)),
                ('acquirer_country_iso', models.CharField(db_index=True, help_text='ISO country code of the acquirer', max_length=3)),
                ('pos_entry_mode', models.CharField(db_index=True, help_text="Point of Sale entry mode (e.g., 'Contactless', 'Chip', etc.)", max_length=50)),
                ('wallet_type', models.CharField(blank=True, db_index=True, help_text="Digital wallet type (e.g., 'Apple Pay', 'Google Pay', etc.)", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created in the database')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'mcp_transactions',
                'ordering': ['-transaction_timestamp'],
                'indexes': [models.Index(fields=['transaction_timestamp', 'card_id'], name='mcp_transac_transac_dd0006_idx'), models.Index(fields=['merchant_id', 'transaction_timestamp'], name='mcp_transac_merchan_6793ee_idx'), models.Index(fields=['issuer_bank_name', 'transaction_timestamp'], name='mcp_transac_issuer__c5cfcf_idx'), models.Index(fields=['mcc_category', 'transaction_timestamp'], name='mcp_transac_mcc_cat_7b3425_idx')],
            },
        ),
    ]
