# Generated by Django 5.2.8 on 2025-11-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCPToolSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tool name', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Tool description')),
                ('input_schema', models.JSONField(help_text='JSON Schema for tool input')),
                ('output_schema', models.JSONField(blank=True, help_text='JSON Schema for tool output', null=True)),
                ('category', models.CharField(choices=[('sql_query', 'SQL Query'), ('sql_info', 'SQL Information'), ('sql_admin', 'SQL Administration'), ('general', 'General')], default='general', max_length=100)),
                ('langchain_tool_class', models.CharField(blank=True, help_text='LangChain tool class name', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mcp_tool_schema',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SQLDatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Connection name/identifier', max_length=255, unique=True)),
                ('database_uri', models.CharField(help_text='Database connection URI', max_length=1024)),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('mssql', 'Microsoft SQL Server'), ('oracle', 'Oracle')], default='postgresql', max_length=50)),
                ('sample_rows_in_table_info', models.IntegerField(default=3, help_text='Number of sample rows to include')),
                ('include_tables', models.JSONField(blank=True, help_text='List of tables to include', null=True)),
                ('exclude_tables', models.JSONField(blank=True, help_text='List of tables to exclude', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sql_database_connection',
            },
        ),
        migrations.CreateModel(
            name='OpenAIMCPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonrpc', models.CharField(default='2.0', help_text='JSON-RPC version', max_length=10)),
                ('method', models.CharField(help_text="MCP method (e.g., 'tools/list', 'tools/call')", max_length=255)),
                ('params', models.JSONField(blank=True, help_text='Request parameters', null=True)),
                ('request_id', models.CharField(db_index=True, help_text='Request identifier', max_length=255)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_request', models.JSONField(blank=True, help_text='Complete raw request', null=True)),
            ],
            options={
                'db_table': 'openai_mcp_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'method'], name='openai_mcp__created_079fbc_idx'), models.Index(fields=['session_id', '-created_at'], name='openai_mcp__session_15e794_idx')],
            },
        ),
        migrations.CreateModel(
            name='MCPRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(help_text='Function or tool called', max_length=255)),
                ('user_query', models.TextField(help_text='Original user query')),
                ('sql_query', models.TextField(blank=True, help_text='Generated SQL query', null=True)),
                ('db_response', models.TextField(blank=True, help_text='Database response', null=True)),
                ('mcp_response', models.TextField(blank=True, help_text='MCP response text', null=True)),
                ('should_continue', models.BooleanField(default=False, help_text='Continue chain of actions?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mcp_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mcp.openaimcprequest')),
            ],
            options={
                'db_table': 'mcp_request_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenAIMCPResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonrpc', models.CharField(default='2.0', max_length=10)),
                ('result', models.JSONField(blank=True, help_text='Success result', null=True)),
                ('error', models.JSONField(blank=True, help_text='Error object if failed', null=True)),
                ('response_id', models.CharField(help_text='Matches request_id', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mcp.openaimcprequest')),
            ],
            options={
                'db_table': 'openai_mcp_response',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('context_data', models.JSONField(blank=True, help_text='Session context and variables', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mcp.sqldatabaseconnection')),
            ],
            options={
                'db_table': 'mcp_session',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique identifier for the transaction (UUID format)', max_length=255, unique=True)),
                ('transaction_timestamp', models.DateTimeField(db_index=True, help_text='Timestamp when the transaction occurred')),
                ('card_id', models.BigIntegerField(db_index=True, help_text='Identifier for the card used in the transaction')),
                ('expiry_date', models.CharField(help_text='Card expiry date in MM/YY format', max_length=10)),
                ('issuer_bank_name', models.CharField(db_index=True, help_text='Name of the bank that issued the card', max_length=255)),
                ('merchant_id', models.BigIntegerField(db_index=True, help_text='Unique identifier for the merchant')),
                ('merchant_mcc', models.IntegerField(db_index=True, help_text='Merchant Category Code (MCC)')),
                ('mcc_category', models.CharField(db_index=True, help_text="Human-readable category of the merchant (e.g., 'Grocery & Food Markets')", max_length=255)),
                ('merchant_city', models.CharField(db_index=True, help_text='City where the merchant is located', max_length=255)),
                ('transaction_type', models.CharField(db_index=True, help_text="Type of transaction (e.g., 'POS', 'Online', etc.)", max_length=50)),
                ('transaction_amount_kzt', models.DecimalField(decimal_places=2, help_text='Transaction amount in Kazakhstani Tenge (KZT)', max_digits=12)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Original amount in original currency (if different from KZT)', max_digits=12, null=True)),
                ('transaction_currency', models.CharField(help_text='Currency code of the transaction (ISO 4217)', max_length=3)),
                ('acquirer_country_iso', models.CharField(db_index=True, help_text='ISO country code of the acquirer', max_length=3)),
                ('pos_entry_mode', models.CharField(db_index=True, help_text="Point of Sale entry mode (e.g., 'Contactless', 'Chip', etc.)", max_length=50)),
                ('wallet_type', models.CharField(blank=True, db_index=True, help_text="Digital wallet type (e.g., 'Apple Pay', 'Google Pay', etc.)", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created in the database')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'mcp_transactions',
                'ordering': ['-transaction_timestamp'],
                'indexes': [models.Index(fields=['transaction_timestamp', 'card_id'], name='mcp_transac_transac_dd0006_idx'), models.Index(fields=['merchant_id', 'transaction_timestamp'], name='mcp_transac_merchan_6793ee_idx'), models.Index(fields=['issuer_bank_name', 'transaction_timestamp'], name='mcp_transac_issuer__c5cfcf_idx'), models.Index(fields=['mcc_category', 'transaction_timestamp'], name='mcp_transac_mcc_cat_7b3425_idx')],
            },
        ),
        migrations.CreateModel(
            name='SQLToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(choices=[('QuerySQLDataBaseTool', 'Query SQL Database'), ('InfoSQLDatabaseTool', 'Get Database Info'), ('ListSQLDatabaseTool', 'List Database Tables'), ('QuerySQLCheckerTool', 'Check SQL Query')], help_text='LangChain SQL tool used', max_length=255)),
                ('tool_input', models.JSONField(help_text='Input parameters for the tool')),
                ('tool_output', models.JSONField(blank=True, help_text='Tool execution result', null=True)),
                ('sql_query', models.TextField(blank=True, help_text='Generated or checked SQL query', null=True)),
                ('query_result', models.JSONField(blank=True, help_text='SQL query results', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='mcp.sqldatabaseconnection')),
                ('mcp_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sql_tool_executions', to='mcp.openaimcprequest')),
            ],
            options={
                'db_table': 'sql_tool_execution',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_name', '-created_at'], name='sql_tool_ex_tool_na_b321ca_idx'), models.Index(fields=['database', '-created_at'], name='sql_tool_ex_databas_bb3bdc_idx')],
            },
        ),
    ]
